winget install -e --id Git.Git --accept-package-agreements --accept-source-agreements
winget install -e --id LINQPad.LINQPad.7
winget install -e --id GitHub.GitHubDesktop
winget install -e --id Neovim.Neovim
winget install -e --id Microsoft.VisualStudio.2022.Community
winget install -e --id Microsoft.SQLServer.2019.Developer
winget install -e --id Microsoft.SQLServerManagementStudio
winget install -e --id SQLite.SQLite
winget install -e --id Microsoft.PowerShell.Preview
winget install -e --id Microsoft.VisualStudioCode
winget install -e --id Insomnia.Insomnia
winget install -e --id dbeaver.dbeaver
winget install -e --id OpenJS.NodeJS
winget install -e --id Docker.DockerDesktop
winget install -e --id Mozilla.Firefox
winget install -e --id Google.Chrome
winget install -e --id Notepad++.Notepad++
winget install -e --id Notion.Notion
winget install -e --id SumatraPDF.SumatraPDF
winget install -e --id Adobe.Acrobat.Reader.64-bit
winget install -e --id JanDeDobbeleer.OhMyPosh
winget install -e --id NGWIN.PicPick
winget install -e --id Bandisoft.Honeyview
winget install -e --id Unity.UnityHub
winget install -e --id JetBrains.Rider.EAP
winget install -e --id JetBrains.CLion.EAP
winget install -e --id OBSProject.OBSStudio
winget install -e --id Microsoft.PCManager
winget install -e --id qBittorrent.qBittorrent
winget install -e --id Telegram.TelegramDesktop
winget install -e --id RARLab.WinRAR
winget install -e --id TorProject.TorBrowser
winget install -e --id ProtonTechnologies.ProtonVPN
winget install -e --id RevoUninstaller.RevoUninstaller
winget install -e --id GlassWire.GlassWire
winget install -e --id VideoLAN.VLC
winget install -e --id Valve.Steam
winget install -e --id EpicGames.EpicGamesLauncher
